### ISSUE TITLE
What's with the number 66?

### ISSUE THREAD

**Issue by vweevers** [deanlandolt/bytespace#14]
It's been a while since I've last kicked the tires. Found a weird bug when using a bytewise keyEncoding on a memdown (latest 1.1.0) db, with numbers for keys. **If I put something in key 66 and 67, then a get of key 66 returns the value for 67. And a readstream only yields key 67.** Other numbers (less than 66 at least, I didn't test > 66) don't have this conflict.

Here's a test case. Sorry for the long code, it took me a while to find the issue. But the gist of the problem is shown in the `testBuffer` function. I was hoping you can shed some light on this; then I can take it to memdown and report or fix whatever the real issue is. Thanks in advance.

```js
var test = require('tape')
  , levelup = require('levelup')
  , memdown = require('memdown')
  , bytespace = require('bytespace')
  , bytewise = require('bytewise-core')

test('magic numbers', function(t) {
  var first = 66
  var second = 67

  // Ok
  t.test('bytewise hex in memdown', function(t) {
    testBytewise(t, mem(), true)
  })

  // Fails
  t.test('bytewise buffer in memdown', function(t) {
    testBytewise(t, mem())
  })

  // Ok
  t.test('bytewise buffer in leveldown', function(t) {
    testBytewise(t, level())
  })

  // Ok
  t.test('buffer in leveldown', function(t) {
    testBuffer(t, level({ keyEncoding: 'binary' }))
  })

  // Fails
  t.test('buffer in memdown', function(t) {
    testBuffer(t, mem({ keyEncoding: 'binary' }))
  })

  function mem(opts) {
    memdown.clearGlobalStore()
    opts = opts || {}
    opts.db = memdown

    return levelup((Math.random()+'').slice(2), opts)
  }

  function level(opts) {
    return levelup('testdb/'+(Math.random()+'').slice(2), opts || {})
  }

  function testBuffer(t, db) {
    t.plan(3)

    var space = bytespace(db, 'root', { keyEncoding: bytewise })
    
    var b1 = space.namespace.encode(first)
    var b2 = space.namespace.encode(second)

    db.put(b1, 'first', function(err) {
      db.get(b1, function(err, value) {
        t.equals(value, 'first', 'first')

        db.put(b2, 'second', function(err) {
          db.get(b2, function(err, value) {
            t.equals(value, 'second', 'second')

            // this returns 'second' in memdown
            db.get(b1, function(err, value) {
              t.equals(value, 'first', 'first (2)')
            })
          })
        })
      })
    })
  }

  function testBytewise(t, db, hex) {
    t.plan(4)

    var space = bytespace(db, 'root', {
      valueEncoding: 'json',
      keyEncoding: bytewise,
      hexNamespace: !!hex
    })

    space.put(first, first, function(err) {
      space.get(first, function(err, v){
        t.equal(v, first, first)

        space.put(second, second, function(err) {
          space.get(second, function(err, v){
            t.equal(v, second, second)

            // the weird part (in memdown): key 66 returns value 67..
            space.get(first, function(err, v){
              t.equal(v, first, first + ' (after setting ' + second + ')')

              // ..yet the stream only collects key 67
              collect(space, function(err, acc) {
                t.deepEqual(acc, [[first,first],[second,second]], 'kv match')
              })
            })
          })
        })
      })
    })
  }
})

function collect(db, cb) {
  var acc = []

  db.createReadStream().on('data', function(kv) {
    acc.push([kv.key, kv.value])
  }).on('finish', function() {
    cb(null, acc)
  }).on('error', cb)
}
```

**Comment by deanlandolt** [comment]
Looks like a *fun* bug...

So from a quick glance at memdown it looks like they're using `ltgt` when iterating over read streams, but [`get` uses the underlying `get` method of the backing RBTree directly](https://github.com/Level/memdown/blob/master/memdown.js#L155). When creating this RBTree [no custom comparator is passed in](https://github.com/Level/memdown/blob/master/memdown.js#L128) so [so it falls back](https://github.com/mikolalysenko/functional-red-black-tree/blob/master/rbtree.js#L995) to its [default comparator](https://github.com/mikolalysenko/functional-red-black-tree/blob/master/rbtree.js#L983-L991) -- which isn't buffer-aware...

I don't know the first thing about what kind of data structures the RBTree is using, but my gut tells me this is the root issue. It'd explain why you're seeing different behavior for gets vs. iterations.

**Comment by vweevers** [comment]
Aah, that makes sense. I had no idea where to look. Using `ltgt` was actually my contribution to memdown.. it's weird that I never saw issues with `get` before. The readstream in the test case above yields a wrong result too, that's probably because `set` ([`insert`](https://github.com/mikolalysenko/functional-red-black-tree/blob/master/rbtree.js#L67), in the red-black tree) also uses the comparator.

Thanks for the response and effort looking into this :+1:, I'll try and see what happens when the RBTree uses `ltgt.compare` as comparator.

**Comment by vweevers** [comment]
Confirmed. PR here: https://github.com/Level/memdown/pull/41

Thanks again!
